#!/bin/bash

LOGFILE=jsbuild.log

# todo: --enable-more-deterministic currently broken but should be common config

COMMON_OPTS="--with-ccache=/usr/local/bin/ccache"
THREAD_OPTS="--with-system-nspr --enable-threadsafe"
DEBUG_OPTS="--enable-debug --disable-optimize --enable-gczeal" 
VALGRIND_OPTS="--disable-jemalloc --enable-valgrind"

NOTHREAD_CONFIG="$COMNON_OPTS $DEBUG_OPTS"
DEBUG_CONFIG="$COMMON_OPTS $DEBUG_OPTS $THREAD_OPTS"
VALGRIND_CONFIG="$COMMON_OPTS $DEBUG_OPTS $THREAD_OPTS $VALGRIND_OPTS"
RELEASE_CONFIG="$COMNON_OPTS"

CLEAN=
DEBUG=
NOTHREAD=
VALGRIND=
RELEASE=

while [ $# -ge 1 ]; do
    case "$1" in
        -c) 
            CLEAN=t
            ;;
        -C) 
            CLEAN=
            ;;
        debug) 
            DEBUG=t
            ;;
        nothread) 
            NOTHREAD=t
            ;;
        release)
            RELEASE=t
            ;;
        valgrind)
            VALGRIND=t
            ;;
        *)  
            echo "jsbuild [-c|-C] [debug|nothread|valgrind|release]"
            echo "  -c => clean first"
            echo "  -C => don't clean first (the default)"
            exit 1
            ;;
    esac
    shift
done

if [ -z "$DEBUG" -a -z "$NOTHREAD" -a -z "$RELEASE" -a -z "$VALGRIND" ]; then
    DEBUG=debug
    RELEASE=release
fi

if [ ! -e ./jsapi.h ]; then
    echo Run jsbuild from the tree/js/src directory
    exit 1
fi

function fail()
{        
    echo "Build failed, see $LOGFILE"
    exit 1
}

function build()
{
    local NAME=$1
    local DIR=$2
    local CONFIG=$3
    local CLEAN=$4

    if [ -n "$CLEAN" ]; then
        echo Clean $NAME
        rm -rf $DIR
    fi

    if [ ! -d $DIR ]; then
        echo Configure $NAME
        mkdir $DIR
        cd $DIR
        echo configure $CONFIG > $LOGFILE
        ../configure $CONFIG >> $LOGFILE 2>&1 || fail
        cd ..
    fi

    echo Build $NAME
    make -C $DIR -j8 >> $DIR/$LOGFILE 2>&1 || fail
}

rm -f $LOGFILE

if [ ! -d debug-build ] && [ ! -d release-build ]; then
    autoconf213 2>&1 > $LOGFILE || fail
fi

if [ -n "$DEBUG" ]; then
    build debug debug-build "$DEBUG_CONFIG" $CLEAN
fi

if [ -n "$NOTHREAD" ]; then
    build nothread nothread-build "$NOTHREAD_CONFIG" $CLEAN
fi

if [ -n "$VALGRIND" ]; then
    build valgrind valgrind-build "$VALGRIND_CONFIG" $CLEAN
fi

if [ -n "$RELEASE" ]; then
    build release release-build "$RELEASE_CONFIG" $CLEAN
fi
