#!/bin/bash

BASE_FILE=$1
REJ_FILE=$BASE_FILE.rej
OUT_FILE=$BASE_FILE.out
ORIG_FILE=$BASE_FILE.orig

if [ $# -ne 1 ]; then
    echo "usage: qwiggle BASE_FILE"
    exit 1
fi

if [ ! -e "$BASE_FILE" ]; then
    echo "Base file not found: $BASE_FILE"
    exit 1
fi

if [ ! -e "$REJ_FILE" ]; then
    echo "Rejects file not found: $REJ_FILE"
    exit 1
fi

wiggle --merge $BASE_FILE $REJ_FILE > $OUT_FILE

if [ $? -ne 0 ]; then
    echo "wiggle failed, merge in $OUT_FILE"
    exit $?
fi

echo "wiggle succeeded, updating $BASE_FILE"
rm -f $ORIG_FILE
mv $BASE_FILE $ORIG_FILE && \
mv $OUT_FILE $BASE_FILE && \
rm $REJ_FILE
